// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ultneeibejhsrdoduths.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsdG5lZWliZWpoc3Jkb2R1dGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTg4ODEsImV4cCI6MjA3Mzc3NDg4MX0.bLxIDiPAcWZ1minYtP1xc__KQGqZLsee88wq5bEmQc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});